version: "3"

# This file should live in a directory about `qmk_api` and `qmk_compiler`
# Eventually we would have some sort of git subdir or something to contain
# this... For now, just cp (or symlink) it up a dir or something.

services:
  qmk_api:
    build: .
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      S3_HOST: http://minio:9000
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
      UPDATE_API: "true"

  qmk_compiler:
    build: ../qmk_compiler
    environment:
      MINIO_ACCESS_KEY: minio_dev
      MINIO_SECRET_KEY: minio_dev_secret
      REDIS_HOST: redis
      S3_HOST: http://minio:9000

  minio:
    image: minio/minio:RELEASE.2018-09-25T21-34-43Z
    volumes:
      - data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_dev
      MINIO_SECRET_KEY: minio_dev_secret
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
    command: server minio_data
    restart: always

  redis:
    image: redis:4.0
    # For some reason this doesn't seem to work...  I still get:
    # `# Warning: no config file specified, using the default config.`
    #volumes:
    # ./redis contains a redis.conf file, /usr/local/etc/redis/
    # is supposedly where redis looks for its conf
    # - ./redis/:/usr/local/etc/redis/
    ports:
      - "6379:6379"
    restart: always

volumes:
  data:
