#!/bin/sh
if [ -d /kle2xy ]; then
    pip install -e /kle2xy
fi

if [ -d /qmk_compiler ]; then
    pip install -e /qmk_compiler
fi

if [ x"$MAX_REQUESTS" = x"" ]; then
    MAX_REQUESTS=1000
fi

if [ x"$MAX_REQUESTS_JITTER" = x"" ]; then
    MAX_REQUESTS_JITTER=100
fi

if [ x"$NUM_WORKERS" = x"" ]; then
    NUM_WORKERS=8
fi

if [ x"$TIMEOUT" = x"" ]; then
    TIMEOUT=60
fi

if [ x"$PORT" = x"" ]; then
    PORT=5000
fi

exec gunicorn -w $NUM_WORKERS -b 0.0.0.0:5000 --max-requests 1000 --max-requests-jitter 100 -t 60 web:app